### ISSUE TITLE
[Tracking issue] — JSR docs design implementation todos

### ISSUE THREAD

**Issue by donjo** [jsr-io/jsr#551]
Creating this as a tracking issue for the few remaining things we had mocked up but are still working on implementing as part of the JSR docs refresh

- [x] #524 
- [x] Line up search for symbols with sidebar content width #538 
- [x] Fix breadcrumb rendering — in some circumstances a breadcrumb may get the increased font size that only the first breadcrumb in the list is supposed to have #529 
- [ ] **Address how to handle H1s defined in markdown** — users who use H1s to style their docs content a certain way may inadvertently mess with the overall document structure of the page given that deno_doc content is rendered as a subset of the total content on the page. This creates a potential styling issue (super large fonts where you don't expect it) and a page structure issue that can impact accessibility, generated in-page navigation, etc.
- [ ] **Sorting symbols on /doc by type** — Right now the docs page on a package lists all symbols in alphabetical order. To make things a bit easier to read we intend to first group the symbols by type and then alphabetize within the type (ex: show all functions first, then classes, then interfaces, etc.) 
- [ ] **Restyling type signatures** (syntax highlighting, multi-line, etc.)
- [ ] **Full page search on symbols page** — dynamically filtering and rendering the list of symbols based on search terms instead of relying on the dropdown

**Comment by typed-sigterm** [comment]
JSR docs page design is the most good-looking API docs design I have ever seen. 🌟 Is there a library/tool behind it?

**Comment by crowlKats** [comment]
@typed-sigterm yes, https://github.com/denoland/deno_doc, which is our own documentation generator
